### ISSUE TITLE
[BUG]: Athena OS is not going to install over NixOS (building problem)

### ISSUE THREAD

**Issue by DDrozdzz-1066** [Athena-OS/athena-nix#10]
### Athena OS version

NixOS 23.11 (Tapir)

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.1.71

### Repro steps

I used the commands:
sudo nix-channel --update,
nix-shell -p git,
git clone https://github.com/Athena-OS/athena-nix,
cd athena-nix/nixos,
sudo cp -rf home-manager hosts modules pkgs users configuration.nix default.nix /etc/nixos/,

and I get an error that reads: 

    The option `services.libinput' does not exist. Definition values:
           - In `/etc/nixos/modules/hardware':
               {
                 enable = true;
               }

which prevented me from installing Athena OS over NixOS.
![Zrzut ekranu z 2024-06-21 17-19-51](https://github.com/Athena-OS/athena-nix/assets/71146814/a323f8ce-6e64-40d1-92a0-e60955ec4b27)

### Expected behavior

I expect to see a properly built Athena operating system and zero errors while building it

### Actual behavior

During the build process, the terminal returned several errors regarding the system build

**Comment by AkechiShiro** [comment]
Hello @DDrozdzz-1066 23.11 is deprecated, please upgrade to 24.05 which is the latest supported release.

**Comment by AkechiShiro** [comment]
The `service.libinput` is defined only for 24.05 and replaces the old `xserver.libinput` which breaks your install right now.

**Comment by AkechiShiro** [comment]
Let me know if I can close this once you have been able to upgrade to 24.05 and install successfully @DDrozdzz-1066

**Comment by AkechiShiro** [comment]
@D3vil0p3r I think we can close this issue
