### ISSUE TITLE
在线安装错误求帮助

### ISSUE THREAD

**Issue by Alan25013** [Athena-OS/athena-nix#112]
## Question
出现 add locales to locale.gen ERROR: no such file or directory (os error 2 )时区准备错误

**Comment by shard77** [comment]
Hey @Alan25013 could you provide more details? What exactly did you install?
Please elaborate so that I can provide support here.

**Comment by Alan25013** [comment]
> 嘿@Alan25013你能提供更多细节吗？你具体安装了什么？ 请详细说明，以便我可以在这里提供支持。

![IMG_20240201_171058](https://github.com/Athena-OS/athena-nix/assets/129571517/357794b3-e437-4faf-bad1-561e1912e351)

**Comment by Alan25013** [comment]
> 嘿@Alan25013你能提供更多细节吗？你具体安装了什么？ 请详细说明，以便我可以在这里提供支持。
请你帮帮我，我已经7天了还没装好

**Comment by ZHANGTIANYAO1** [comment]
大哥你这照片认真的吗？ 你觉得这个反光能看清楚什么......
请提供`/tmp/aegis.log` and `/tmp/config.json` 这两个日志文件给开发者
还有就是项目现在迁移到nix os了优先尝试新版本（pre release）

**Comment by ZHANGTIANYAO1** [comment]
> 。

还有就是这个错误很可能是你没联网，先联网

**Comment by D3vil0p3r** [comment]
Old ISO
