### ISSUE TITLE
[QUESTION]: What's the relationship with Arch Linux

### ISSUE THREAD

**Issue by clsty** [Athena-OS/athena-nix#119]
## Question

I've noticed that the logo contains the triangle similar to the logo of Arch Linux.

Also, in [doc site](https://athenaos.org) Arch Linux and even AUR are mentioned several times.

So, what's the relationship between Athena-OS and Arch Linux?

---

I also wish this question could be document in that doc site. Thanks in advance!

**Comment by D3vil0p3r** [comment]
Hello! Athena was based on Arch. Currently we are still migrate resources from Arch to Nix, and we need still to change illustrations too.

**Comment by clsty** [comment]
I see. Guess you'll make the Athena waving a "Flake" logo shield then lol

**Comment by D3vil0p3r** [comment]
Lets see what come in our mind
