### ISSUE TITLE
[QUESTION]: How can I fix errors with lib.mdDoc, home manager, and services, that I sent in screenshot? 

### ISSUE THREAD

**Issue by DDrozdzz-1066** [Athena-OS/athena-nix#15]
Hello
I recently used the command “sudo nixos-rebuild switch --upgrade” and I got several warnings with lib.MDdoc, home manager and three services that were renamed. Some applications have stopped opening for me, making the system less functional, so I'm trying to solve these problems somehow. How can I bring the system to a more functional state?

![Screenshot from 2024-07-28 19-33-12](https://github.com/user-attachments/assets/4726e480-d2dc-4f42-a031-3bee4519dc19)

**Comment by AkechiShiro** [comment]
This error seems to be a bit tricky because `home-manager` in unstable is following `24.11` but the documentation seems to state that `unstable` is for `24.05`.

I think this issue upstream is related to your issue : https://github.com/nix-community/home-manager/issues/5476

**Comment by AkechiShiro** [comment]
@D3vil0p3r could you close this issue as `not planned` or `fixed/responded` to
