### ISSUE TITLE
[ENHANCEMENT]: Forensics tools suggestion

### ISSUE THREAD

**Issue by MikeHorn-git** [Athena-OS/athena-nix#17]
- [acquire](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/python-modules/acquire/default.nix#L60) : Tool to quickly gather forensic artifacts from disk images or a live system
- [fatcat](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/development/tools/fatcat/default.nix#L28) : FAT filesystems explore, extract, repair, and forensic tool
- [file](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/tools/misc/file/default.nix#L46) : A program that shows the type of files
- [hstsparser](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/tools/security/hstsparser/default.nix#L31) : Tool to parse Firefox and Chrome HSTS databases into forensic artifacts
- [mac-robber](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/ma/mac-robber/package.nix#L36) : A digital investigation tool that collects data from allocated files in a mounted file system
- [ntfs-3g](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/tools/filesystems/ntfs-3g/default.nix#L57) : FUSE-based NTFS driver with full write support
- [osquery](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/tools/system/osquery/default.nix#L87) : SQL powered operating system instrumentation, monitoring, and analytics
- [prowler](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/pr/prowler/package.nix#L84) : Security tool for AWS, Azure and GCP to perform Cloud Security best practices assessments
- [scalpel](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/by-name/sc/scalpel/package.nix#L50) : Recover files based on their headers, footers and internal data structures, based on Foremost
- [tracee](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/tools/security/tracee/default.nix#L92) : Linux Runtime Security and Forensics using eBPF

**Comment by AkechiShiro** [comment]
Hi @MikeHorn-git thanks for the suggestion, we'll also be working on adding the tools from : https://tsurugi-linux.org/documentation_tsurugi_linux_tools_listing_2024.php

As best as possible given some tools licenses.

We'll be working on a tracker to let the community vote which package should be the priority, `ntfs-3g` is packaged already, you can find packages by query here : https://search.nixos.org/packages?query=<pkg_name> 

- [X] acquire
- [X] osquery
- [X] fatcat
- [X] mac-robber
- [X] ntfs-3g
- [X] file
- [X] prowler
- [X] scalpel
- [X] tracee

All of the tools are already packaged, they only need to be added in the `forensic` role, I'll try and see if I can PR this and @D3vil0p3r may review

**Comment by D3vil0p3r** [comment]
Added in forensic role.
