### ISSUE TITLE
[BUG]: xfce, kde, gnome do not autostart in latest .iso

### ISSUE THREAD

**Issue by skinnypuppy** [Athena-OS/athena-nix#19]
### Athena OS version

23.10

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

Installed latest .iso trying xfce refind, kde and gnome. Install boots straight to terminal, no DE.

### Expected behavior

Install should boot to DE after install.

### Actual behavior

Boots to terminal only.

**Comment by AkechiShiro** [comment]
Is this still relevant today ? @skinnypuppy

**Comment by skinnypuppy** [comment]
No, the .iso has been fixed by the developer.

**Comment by AkechiShiro** [comment]
Yeah it is built automatically/updated as well I believe, glad this was fixed.
