### ISSUE TITLE
Any way community can help with this big change other than just testing ?

### ISSUE THREAD

**Issue by AkechiShiro** [Athena-OS/athena-nix#2]

**Comment by ghost** [comment]
If you know how to package software in nixpkgs, or you're willing to learn, see: https://github.com/NixOS/nixpkgs/issues/81418

**Comment by AkechiShiro** [comment]
Can I just fork this and update it with the new packages ?

https://github.com/JJJollyjim/arewehackersyet

I can also package in nixpkgs, and have packaged BloodHound for instance, but I need to work on more, as there is still quite a few packages that are still missing.
