### ISSUE TITLE
[BUG]: Crackmapexec is considered broken

### ISSUE THREAD

**Issue by ghost** [Athena-OS/athena-nix#23]
### Athena OS version

Athena OS 24.11 (Vicuna): 24.11pre696158.2768c7d042a3

### Which environment or technology are you using?

- [ ] Baremetal
- [ ] VirtualBox Virtual Machine
- [X] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.6.58

### Involved software

crackmapexec

### Repro steps

Run sudo nixos-rebuild switch after a fresh rolling release install.

### Expected behavior

The nixos-rebuild switch complete successfully without problems.

### Actual behavior

`nixos-rebuild switch` fails because crackmapexec is unmaintained and broken, i lost the logs files, but it is similar to this one:
```
error: Package ‘crackmapexec-x’ in /nix/store/xxxx is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

**Comment by ghost** [comment]
Crackmapexec is evaluated in `/etc/nixos/modules/cyber/roles/red.nix`, line 64. A temporary workaround is commenting this line like this:
```
#crackmapexec
```
And using netexec instead, which is a maintained fork of crackmapexec.

**Comment by D3vil0p3r** [comment]
Thanks. Fixed upstream as suggested
