### ISSUE TITLE
[BUG]: the tools are not working and the welcome screen didn't show even

### ISSUE THREAD

**Issue by unknownskuller** [Athena-OS/athena-nix#5]
### Athena OS version

\

### Which environment or technology are you using?

- [ ] Baremetal
- [X] VirtualBox Virtual Machine
- [X] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

[

### Involved software

[

### Repro steps

[

### Expected behavior

[

### Actual behavior

[

### Diagnostic logs

[

**Comment by unknownskuller** [comment]
tools are not working and the welcome screen didn't show up

**Comment by AkechiShiro** [comment]
I'd say this issue should be closed, you're not describing what issue you encountered nor any error, nor any screenshots of your issue.

Sorry but nobody can help you if you don't put in any efforts.

@D3vil0p3r could you please, close it ?

**Comment by D3vil0p3r** [comment]
I would like to verify Athena Nix about Athena Welcome. After that, I think I can close it.

**Comment by unknownskuller** [comment]
> I'd say this issue should be closed, you're not describing what issue you encountered nor any error, nor any screenshots of your issue.
> 
> Sorry but nobody can help you if you don't put in any efforts.
> 
> @D3vil0p3r could you please, close it ?

![Athena OS  Running  - Oracle VM VirtualBox 4_15_2024 7_27_57 PM](https://github.com/Athena-OS/athena-nix/assets/156254749/0e374730-a5a4-4834-ae41-d29bd77d3d8b)
![Athena OS  Running  - Oracle VM VirtualBox 4_15_2024 7_28_48 PM](https://github.com/Athena-OS/athena-nix/assets/156254749/50ac8507-488d-463a-9335-b887fc3198b9)

**Comment by D3vil0p3r** [comment]
Yes. I know it. Download again the ISO. I uploaded a working ISO fixing that issue.

**Comment by unknownskuller** [comment]
> Yes. I know it. Download again the ISO. I uploaded a working ISO fixing that issue.

so i download it again yeah ? you fixed that

**Comment by AkechiShiro** [comment]
@unknownskuller he said he did fix it, is it fixed for you ?

**Comment by unknownskuller** [comment]
> @unknownskuller he said he did fix it, is it fixed for you ?

i will try it aging and see if it is fixed

**Comment by unknownskuller** [comment]
> Yes. I know it. Download again the ISO. I uploaded a working ISO fixing that issue.

the online and offline install is not appearing and the welcome screen is working good

**Comment by D3vil0p3r** [comment]
So can we close this issue?
