### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by corvinux** [Athena-OS/athena-nix#8]
### Athena OS version

Distributor ID:	Athena OS Description:	Athena OS 24.11 (Vicuña) Release:	24.11 Codename:	vicuña

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Kernel version

6.6.32

### Repro steps

 sudo nixos-rebuild switch --flake /etc/nixos#runtime --impure
error:
       … while calling the 'seq' builtin

         at /nix/store/kp9wqy67xsqd2ccmyqr5zg2g90yjly73-source/lib/modules.nix:322:18:

          321|         options = checked options;
          322|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          323|         _module = checked (config._module);

       … while evaluating a branch condition

         at /nix/store/kp9wqy67xsqd2ccmyqr5zg2g90yjly73-source/lib/modules.nix:261:9:

          260|       checkUnmatched =
          261|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [] then
             |         ^
          262|           let

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: getting status of '/nix/store/nr3z3h2wb9cn5i1p7fs5m4dybpq8rvd0-source/nixos': No such file or directory

### Expected behavior

No errors

### Actual behavior

error:
       … while calling the 'seq' builtin

         at /nix/store/kp9wqy67xsqd2ccmyqr5zg2g90yjly73-source/lib/modules.nix:322:18:

          321|         options = checked options;
          322|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          323|         _module = checked (config._module);

       … while evaluating a branch condition

         at /nix/store/kp9wqy67xsqd2ccmyqr5zg2g90yjly73-source/lib/modules.nix:261:9:

          260|       checkUnmatched =
          261|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [] then
             |         ^
          262|           let

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: getting status of '/nix/store/nr3z3h2wb9cn5i1p7fs5m4dybpq8rvd0-source/nixos': No such file or directory

**Comment by AkechiShiro** [comment]
Not sure what is your config, but we can't help without much info

**Comment by AkechiShiro** [comment]
Feel free to share the configuration or if you cannot, we'll have to close this issue, we can't help you without the configuration that doesn't work

@D3vil0p3r : I'll let you choose when we should close this issue
