### ISSUE TITLE
[BUG]: Installation(Online) error

### ISSUE THREAD

**Issue by deepinsideDrury** [Athena-OS/athena-nix#95]
### Athena OS version

Athena OS live

### Which environment or technology are you using?

- [X] Baremetal
- [ ] VirtualBox Virtual Machine
- [ ] VMware Virtual Machine
- [ ] Hyper-V Virtual Machine
- [ ] QEMU/KVM
- [ ] Parallels
- [ ] UTM
- [ ] Container
- [ ] WSL

### Repro steps

Installation(Online)
[Select Keyboard Layout]
Region China
[Select Timezone]
Region Asia
Zone Shanghai

### Expected behavior

install success

### Actual behavior

error

### Diagnostic logs

[install.log](https://github.com/Athena-OS/athena-iso/files/13626880/install.log)

**Comment by zennvoan12** [comment]
same case

**Comment by sd1471123** [comment]
same case +1

**Comment by D3vil0p3r** [comment]
I uploaded a new ISO where I removed BA. Download it and try. Note that for users from China probably you need a VPN.
